# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_BQ27426_FG_MMI)	+= bq27426_fg_mmi/
obj-$(CONFIG_MMI_CHARGER)	+= mmi_charger/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE) += qpnp_adaptive_charge/
